import { AlertCircle, CalendarDays, ChevronLeft, ChevronRight, Clock3, Eye, FilterX, LoaderCircle, Pencil, Plus, RefreshCw, Search, Trash2, UserRound, Stethoscope } from 'lucide-react';
import { useCallback,useEffect,useState,type FormEvent } from 'react';
import { useSearchParams } from 'react-router-dom';
import { AppointmentForm } from '../components/AppointmentForm';
import { Modal } from '../components/Modal';
import { appointmentOptionsRequest,createAppointmentRequest,deleteAppointmentRequest,listAppointmentsRequest,updateAppointmentRequest } from '../services/appointmentApi';
import { APPOINTMENT_STATUSES,type Appointment,type AppointmentListResponse,type AppointmentOptions,type AppointmentPayload,type AppointmentStatus } from '../types/appointment';

const fmt=(v:string)=>new Date(`${v}T00:00:00`).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'});
export const AppointmentsPage=()=>{
 const [searchParams]=useSearchParams();
 const [result,setResult]=useState<AppointmentListResponse|null>(null),[options,setOptions]=useState<AppointmentOptions>({patients:[],doctors:[]});
 const [loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[searchInput,setSearchInput]=useState(''),[search,setSearch]=useState('');
 const [status,setStatus]=useState<AppointmentStatus|''>(''),[doctorId,setDoctorId]=useState(searchParams.get('doctorId')??''),[dateFrom,setDateFrom]=useState(''),[dateTo,setDateTo]=useState(''),[page,setPage]=useState(1);
 const [formMode,setFormMode]=useState<'create'|'edit'|null>(null),[selected,setSelected]=useState<Appointment|null>(null),[details,setDetails]=useState<Appointment|null>(null),[removing,setRemoving]=useState<Appointment|null>(null);
 const [submitting,setSubmitting]=useState(false),[formError,setFormError]=useState<string|null>(null),[toast,setToast]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);try{const [data,opts]=await Promise.all([listAppointmentsRequest({search:search||undefined,status:status||undefined,doctorId:doctorId||undefined,dateFrom:dateFrom||undefined,dateTo:dateTo||undefined,page,limit:10}),appointmentOptionsRequest()]);setResult(data);setOptions(opts);setError(null);}catch(e){setError(e instanceof Error?e.message:'Unable to load appointments.');}finally{setLoading(false);}},[search,status,doctorId,dateFrom,dateTo,page]);
 useEffect(()=>{void load();},[load]);useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(null),3500);return()=>clearTimeout(t);},[toast]);
 const save=async(payload:AppointmentPayload)=>{setSubmitting(true);setFormError(null);try{if(formMode==='edit'&&selected)await updateAppointmentRequest(selected.id,payload);else await createAppointmentRequest(payload);setToast(formMode==='edit'?'Appointment updated.':'Appointment scheduled.');setFormMode(null);setSelected(null);await load();}catch(e){setFormError(e instanceof Error?e.message:'Unable to save appointment.');}finally{setSubmitting(false);}};
 const remove=async()=>{if(!removing)return;setSubmitting(true);try{await deleteAppointmentRequest(removing.id);setRemoving(null);setToast('Appointment removed.');await load();}catch(e){setToast(e instanceof Error?e.message:'Delete failed.');}finally{setSubmitting(false);}};
 const filtered=Boolean(search||status||doctorId||dateFrom||dateTo);const rows=result?.appointments??[];
 return <div className="dashboard-page appointments-page">
  <section className="page-heading"><div><p className="eyebrow">Clinical scheduling</p><h2>Appointment management</h2><p>Coordinate patients and doctors with protected slot validation.</p></div><button className="button button--primary" onClick={()=>{setSelected(null);setFormError(null);setFormMode('create');}}><Plus size={17}/> Schedule appointment</button></section>
  <section className="patient-summary"><article><span><CalendarDays size={21}/></span><div><strong>{result?.pagination.total??'—'}</strong><small>{filtered?'Matching appointments':'Appointments'}</small></div></article><article><span><UserRound size={21}/></span><div><strong>{options.patients.length}</strong><small>Active patients</small></div></article><article><span><Stethoscope size={21}/></span><div><strong>{options.doctors.length}</strong><small>Active doctors</small></div></article></section>
  <section className="panel patient-directory"><div className="patient-toolbar"><form className="patient-search" onSubmit={(e:FormEvent)=>{e.preventDefault();setPage(1);setSearch(searchInput.trim());}}><Search size={17}/><input value={searchInput} onChange={e=>setSearchInput(e.target.value)} placeholder="Search appointment, patient, doctor, or reason"/><button>Search</button></form><div className="patient-filters appointment-filters"><select value={status} onChange={e=>{setStatus(e.target.value as AppointmentStatus|'');setPage(1);}}><option value="">All statuses</option>{APPOINTMENT_STATUSES.map(s=><option key={s}>{s}</option>)}</select><select value={doctorId} onChange={e=>{setDoctorId(e.target.value);setPage(1);}}><option value="">All doctors</option>{options.doctors.map(d=><option value={d.id} key={d.id}>{d.name}</option>)}</select><input type="date" value={dateFrom} onChange={e=>{setDateFrom(e.target.value);setPage(1);}}/><input type="date" value={dateTo} onChange={e=>{setDateTo(e.target.value);setPage(1);}}/>{filtered&&<button className="icon-button icon-button--bordered" onClick={()=>{setSearch('');setSearchInput('');setStatus('');setDoctorId('');setDateFrom('');setDateTo('');setPage(1);}}><FilterX size={16}/></button>}</div></div>
  {error?<div className="table-state table-state--error"><AlertCircle size={28}/><strong>Appointments could not be loaded</strong><p>{error}</p><button className="button button--small" onClick={()=>void load()}><RefreshCw size={15}/> Retry</button></div>:loading?<div className="table-state"><LoaderCircle className="spin" size={28}/><strong>Loading appointments…</strong></div>:!rows.length?<div className="table-state"><CalendarDays size={30}/><strong>{filtered?'No appointments match':'No appointments scheduled'}</strong><p>{filtered?'Clear filters to see other records.':'Create patients and doctors, then schedule the first appointment.'}</p></div>:<><div className="table-scroll"><table className="patients-table appointments-table"><thead><tr><th>Appointment</th><th>Patient</th><th>Doctor</th><th>Date & time</th><th>Reason</th><th>Status</th><th></th></tr></thead><tbody>{rows.map(a=><tr key={a.id}><td><strong className="table-primary">{a.appointmentId}</strong></td><td><strong className="table-primary">{a.patient.fullName}</strong><small className="table-secondary">{a.patient.patientId}</small></td><td><strong className="table-primary">{a.doctor.name}</strong><small className="table-secondary">{a.doctor.specialization}</small></td><td><strong className="table-primary">{fmt(a.appointmentDate)}</strong><small className="table-secondary"><Clock3 size={11}/> {a.appointmentTime}</small></td><td><span className="reason-text">{a.reason}</span></td><td><span className={`status-badge status-badge--${a.status.toLowerCase().replace(' ','-')}`}>{a.status}</span></td><td><div className="row-actions"><button onClick={()=>setDetails(a)}><Eye size={16}/></button><button onClick={()=>{setSelected(a);setFormError(null);setFormMode('edit');}}><Pencil size={15}/></button><button className="row-action--danger" onClick={()=>setRemoving(a)}><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div><footer className="table-pagination"><p>Showing <strong>{rows.length}</strong> of <strong>{result?.pagination.total}</strong></p><div><button className="icon-button icon-button--bordered" disabled={page<=1} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={17}/></button><span>Page {page} of {Math.max(result?.pagination.totalPages??1,1)}</span><button className="icon-button icon-button--bordered" disabled={page>=(result?.pagination.totalPages??1)} onClick={()=>setPage(p=>p+1)}><ChevronRight size={17}/></button></div></footer></>}
  </section>
  {formMode&&<Modal size="large" title={formMode==='edit'?'Edit appointment':'Schedule appointment'} subtitle={selected?.appointmentId} onClose={()=>!submitting&&setFormMode(null)}><AppointmentForm appointment={formMode==='edit'?selected??undefined:undefined} options={options} isSubmitting={submitting} error={formError} onSubmit={save} onCancel={()=>setFormMode(null)}/></Modal>}
  {details&&<Modal title={details.appointmentId} subtitle={`${fmt(details.appointmentDate)} at ${details.appointmentTime}`} onClose={()=>setDetails(null)}><div className="patient-details"><div className="detail-grid"><div><span>Patient</span><strong>{details.patient.fullName} · {details.patient.patientId}</strong></div><div><span>Doctor</span><strong>{details.doctor.name}</strong></div><div><span>Status</span><strong>{details.status}</strong></div><div><span>Date and time</span><strong>{fmt(details.appointmentDate)} · {details.appointmentTime}</strong></div></div><section><h3>Reason</h3><p>{details.reason}</p></section><section><h3>Notes</h3><p>{details.notes??'No notes recorded.'}</p></section></div></Modal>}
  {removing&&<Modal size="small" title="Delete appointment?" onClose={()=>setRemoving(null)}><div className="delete-confirm"><span><Trash2 size={23}/></span><p><strong>{removing.appointmentId}</strong> will be removed from active scheduling records.</p><div><button className="button" onClick={()=>setRemoving(null)}>Cancel</button><button className="button button--danger" onClick={()=>void remove()}>{submitting?<LoaderCircle className="spin" size={16}/>:<Trash2 size={16}/>} Delete</button></div></div></Modal>}
  {toast&&<div className="toast" role="status"><span>✓</span>{toast}</div>}
 </div>;
};
