import type pg from 'pg';import type{Admission,AdmissionInput,AdmissionOptions,AdmissionStatus,AdmissionUpdate,Bed,BedInput,BedStatus,BedType}from'../models/Admission.js';import{AppError}from'../utils/AppError.js';
interface BedRow{id:string;bed_number:string;ward:string;type:BedType;status:BedStatus;patient_uuid:string|null;patient_number:string|null;patient_name:string|null;created_at:Date;updated_at:Date;}
interface AdmissionRow{id:string;admission_id:string;patient_uuid:string;patient_number:string;patient_name:string;doctor_uuid:string;doctor_number:string;doctor_name:string;bed_uuid:string;bed_number:string;ward:string;bed_type:BedType;admission_date:string|Date;expected_discharge:string|Date|null;discharge_date:Date|null;diagnosis:string;status:AdmissionStatus;created_at:Date;updated_at:Date;}
const BC=`b.id,b.bed_number,b.ward,b.type,b.status,p.id patient_uuid,p.patient_id patient_number,p.full_name patient_name,b.created_at,b.updated_at`;
const AC=`a.id,a.admission_id,p.id patient_uuid,p.patient_id patient_number,p.full_name patient_name,d.id doctor_uuid,d.doctor_id doctor_number,d.name doctor_name,b.id bed_uuid,b.bed_number,b.ward,b.type bed_type,a.admission_date,a.expected_discharge,a.discharge_date,a.diagnosis,a.status,a.created_at,a.updated_at`;
const date=(v:string|Date)=>v instanceof Date?v.toISOString().slice(0,10):v;
const bed=(r:BedRow):Bed=>({id:r.id,bedNumber:r.bed_number,ward:r.ward,type:r.type,status:r.status,currentPatient:r.patient_uuid?{id:r.patient_uuid,patientId:r.patient_number!,fullName:r.patient_name!}:null,createdAt:r.created_at.toISOString(),updatedAt:r.updated_at.toISOString()});
const admission=(r:AdmissionRow):Admission=>({id:r.id,admissionId:r.admission_id,patient:{id:r.patient_uuid,patientId:r.patient_number,fullName:r.patient_name},doctor:{id:r.doctor_uuid,doctorId:r.doctor_number,name:r.doctor_name},bed:{id:r.bed_uuid,bedNumber:r.bed_number,ward:r.ward,type:r.bed_type},admissionDate:date(r.admission_date),expectedDischarge:r.expected_discharge?date(r.expected_discharge):null,dischargeDate:r.discharge_date?.toISOString()??null,diagnosis:r.diagnosis,status:r.status,createdAt:r.created_at.toISOString(),updatedAt:r.updated_at.toISOString()});
export interface IAdmissionRepository{listBeds(search?:string,status?:BedStatus,ward?:string):Promise<Bed[]>;createBed(i:BedInput):Promise<Bed>;updateBed(id:string,i:Partial<BedInput>):Promise<Bed|null>;deleteBed(id:string):Promise<boolean>;findBed(id:string):Promise<Bed|null>;listAdmissions(search?:string,status?:AdmissionStatus,ward?:string):Promise<Admission[]>;findAdmission(id:string):Promise<Admission|null>;admit(i:AdmissionInput):Promise<Admission>;updateAdmission(id:string,i:AdmissionUpdate):Promise<Admission|null>;discharge(id:string):Promise<Admission>;deleteAdmission(id:string):Promise<boolean>;options():Promise<AdmissionOptions>;}
export class PostgreSQLAdmissionRepository implements IAdmissionRepository{constructor(private pool:pg.Pool){}
 async listBeds(search?:string,status?:BedStatus,ward?:string){const c=['b.deleted_at IS NULL'],v:unknown[]=[];const add=(x:unknown)=>{v.push(x);return`$${v.length}`};if(search){const p=add(`%${search}%`);c.push(`(b.bed_number ILIKE ${p} OR b.ward ILIKE ${p})`)}if(status)c.push(`b.status=${add(status)}`);if(ward)c.push(`LOWER(b.ward)=LOWER(${add(ward)})`);const r=await this.pool.query<BedRow>(`SELECT ${BC} FROM beds b LEFT JOIN patients p ON p.id=b.current_patient_id WHERE ${c.join(' AND ')} ORDER BY b.ward,b.bed_number`,v);return r.rows.map(bed)}
 async findBed(id:string){const r=await this.pool.query<BedRow>(`SELECT ${BC} FROM beds b LEFT JOIN patients p ON p.id=b.current_patient_id WHERE (b.id::text=$1 OR (b.ward||':'||b.bed_number)=$1) AND b.deleted_at IS NULL`,[id]);return r.rows[0]?bed(r.rows[0]):null}
 async createBed(i:BedInput){const r=await this.pool.query<{id:string}>(`INSERT INTO beds(bed_number,ward,type,status)VALUES($1,$2,$3,$4)RETURNING id`,[i.bedNumber,i.ward,i.type,i.status]);return(await this.findBed(r.rows[0]!.id))!}
 async updateBed(id:string,i:Partial<BedInput>){const m:Array<[keyof BedInput,string]>=[['bedNumber','bed_number'],['ward','ward'],['type','type'],['status','status']],v:unknown[]=[],a:string[]=[];for(const[k,c]of m)if(i[k]!==undefined){v.push(i[k]);a.push(`${c}=$${v.length}`)}v.push(id);const r=await this.pool.query<{id:string}>(`UPDATE beds SET ${a.join(',')},updated_at=NOW() WHERE id::text=$${v.length} AND deleted_at IS NULL AND status<>'Occupied' RETURNING id`,v);return r.rows[0]?this.findBed(r.rows[0].id):null}
 async deleteBed(id:string){const r=await this.pool.query(`UPDATE beds SET deleted_at=NOW(),updated_at=NOW() WHERE id::text=$1 AND deleted_at IS NULL AND status<>'Occupied'`,[id]);return(r.rowCount??0)>0}
 async listAdmissions(search?:string,status?:AdmissionStatus,ward?:string){const c=['a.deleted_at IS NULL'],v:unknown[]=[];const add=(x:unknown)=>{v.push(x);return`$${v.length}`};if(search){const p=add(`%${search}%`);c.push(`(a.admission_id ILIKE ${p} OR p.full_name ILIKE ${p} OR d.name ILIKE ${p} OR a.diagnosis ILIKE ${p})`)}if(status)c.push(`a.status=${add(status)}`);if(ward)c.push(`LOWER(b.ward)=LOWER(${add(ward)})`);const r=await this.pool.query<AdmissionRow>(`SELECT ${AC} FROM admissions a JOIN patients p ON p.id=a.patient_id JOIN doctors d ON d.id=a.doctor_id JOIN beds b ON b.id=a.bed_id WHERE ${c.join(' AND ')} ORDER BY a.admission_date DESC`,v);return r.rows.map(admission)}
 async findAdmission(id:string){const r=await this.pool.query<AdmissionRow>(`SELECT ${AC} FROM admissions a JOIN patients p ON p.id=a.patient_id JOIN doctors d ON d.id=a.doctor_id JOIN beds b ON b.id=a.bed_id WHERE (a.id::text=$1 OR a.admission_id=$1) AND a.deleted_at IS NULL`,[id]);return r.rows[0]?admission(r.rows[0]):null}
 async admit(i:AdmissionInput){const c=await this.pool.connect();try{await c.query('BEGIN');const pr=await c.query(`SELECT 1 FROM patients WHERE id=$1 AND deleted_at IS NULL`,[i.patientId]);if(!pr.rows[0])throw new AppError(400,'INVALID_PATIENT','Select an active patient.');const dr=await c.query(`SELECT 1 FROM doctors WHERE id=$1 AND deleted_at IS NULL`,[i.doctorId]);if(!dr.rows[0])throw new AppError(400,'INVALID_DOCTOR','Select an active doctor.');const br=await c.query<{id:string;ward:string;status:BedStatus}>(`SELECT id,ward,status FROM beds WHERE id=$1 AND deleted_at IS NULL FOR UPDATE`,[i.bedId]);const b=br.rows[0];if(!b)throw new AppError(400,'INVALID_BED','Select an active bed.');if(b.status!=='Available')throw new AppError(409,'BED_NOT_AVAILABLE','The selected bed is not available.');const active=await c.query(`SELECT 1 FROM admissions WHERE patient_id=$1 AND status='Admitted' AND deleted_at IS NULL`,[i.patientId]);if(active.rows[0])throw new AppError(409,'PATIENT_ALREADY_ADMITTED','This patient already has an active admission.');const r=await c.query<{id:string}>(`INSERT INTO admissions(patient_id,doctor_id,bed_id,ward,admission_date,expected_discharge,diagnosis)VALUES($1,$2,$3,$4,$5,$6,$7)RETURNING id`,[i.patientId,i.doctorId,i.bedId,b.ward,i.admissionDate,i.expectedDischarge,i.diagnosis]);await c.query(`UPDATE beds SET status='Occupied',current_patient_id=$1,updated_at=NOW() WHERE id=$2`,[i.patientId,i.bedId]);await c.query('COMMIT');return(await this.findAdmission(r.rows[0]!.id))!}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
 async updateAdmission(id:string,i:AdmissionUpdate){const m:Array<[keyof AdmissionUpdate,string]>=[['doctorId','doctor_id'],['expectedDischarge','expected_discharge'],['diagnosis','diagnosis']],v:unknown[]=[],a:string[]=[];for(const[k,col]of m)if(i[k]!==undefined){v.push(i[k]);a.push(`${col}=$${v.length}`)}v.push(id);const r=await this.pool.query<{id:string}>(`UPDATE admissions SET ${a.join(',')},updated_at=NOW() WHERE id::text=$${v.length} AND deleted_at IS NULL RETURNING id`,v);return r.rows[0]?this.findAdmission(r.rows[0].id):null}
 async discharge(id:string){const c=await this.pool.connect();try{await c.query('BEGIN');const r=await c.query<{id:string;bed_id:string;status:AdmissionStatus}>(`SELECT id,bed_id,status FROM admissions WHERE id::text=$1 AND deleted_at IS NULL FOR UPDATE`,[id]);const a=r.rows[0];if(!a)throw new AppError(404,'ADMISSION_NOT_FOUND','Admission was not found.');if(a.status!=='Admitted')throw new AppError(409,'ADMISSION_NOT_ACTIVE','Only an active admission can be discharged.');await c.query(`UPDATE admissions SET status='Discharged',discharge_date=NOW(),updated_at=NOW() WHERE id=$1`,[a.id]);await c.query(`UPDATE beds SET status='Available',current_patient_id=NULL,updated_at=NOW() WHERE id=$1`,[a.bed_id]);await c.query('COMMIT');return(await this.findAdmission(a.id))!}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
 async deleteAdmission(id:string){const r=await this.pool.query(`UPDATE admissions SET deleted_at=NOW(),updated_at=NOW() WHERE id::text=$1 AND deleted_at IS NULL AND status<>'Admitted'`,[id]);return(r.rowCount??0)>0}
 async options(){const[patients,doctors,beds]=await Promise.all([this.pool.query<{id:string;patient_id:string;full_name:string}>(`SELECT id,patient_id,full_name FROM patients WHERE deleted_at IS NULL ORDER BY full_name`),this.pool.query<{id:string;doctor_id:string;name:string}>(`SELECT id,doctor_id,name FROM doctors WHERE deleted_at IS NULL ORDER BY name`),this.listBeds(undefined,'Available')]);return{patients:patients.rows.map(p=>({id:p.id,patientId:p.patient_id,fullName:p.full_name})),doctors:doctors.rows.map(d=>({id:d.id,doctorId:d.doctor_id,name:d.name})),availableBeds:beds}}
}
