const api=process.env.API_URL??'http://127.0.0.1:5173/api',password=process.env.HMS_TEST_PASSWORD;if(!password){console.error('HMS_TEST_PASSWORD required');process.exit(1);}const json=async r=>{const t=await r.text();return t?JSON.parse(t):null;};const login=async(email)=>{const r=await fetch(`${api}/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});return r.headers.get('set-cookie')?.split(';')[0];};const req=async(path,cookie,init={})=>{const r=await fetch(api+path,{...init,headers:{Cookie:cookie,...(init.body?{'Content-Type':'application/json'}:{}),...init.headers}});return{r,b:await json(r)}};
const run=async()=>{const admin=await login('admin@medicore.test'),doctorUser=await login('doctor@medicore.test'),reception=await login('reception@medicore.test');if(!admin)throw Error('login failed');for(const c of [doctorUser,reception])if((await req('/appointments',c)).r.status!==200)throw Error('authorized role denied');const u=Date.now();let p,d,a;try{
 p=(await req('/patients',admin,{method:'POST',body:JSON.stringify({fullName:`Appointment Patient ${u}`,dateOfBirth:'1995-05-10',gender:'Other',bloodGroup:'B+',phone:'+91 9000011111',email:`apt-p-${u}@test.local`,address:'Test Pune Address',emergencyContact:'Contact +91 9888811111',reasonForVisit:'Appointment workflow',medicalHistory:null})})).b.patient;
 d=(await req('/doctors',admin,{method:'POST',body:JSON.stringify({name:`Dr. Appointment ${u}`,specialization:'Scheduling',department:'Workflow',phone:'+91 9000022222',email:`apt-d-${u}@test.local`,room:'A-101',consultationFee:500,availability:[{day:'Monday',startTime:'09:00',endTime:'17:00'}]})})).b.doctor;
 const tomorrow=new Date(Date.now()+86400000).toISOString().slice(0,10),payload={patientId:p.id,doctorId:d.id,appointmentDate:tomorrow,appointmentTime:'10:30',reason:'Phase 5 verification',status:'Scheduled',notes:'Database workflow'};
 let x=await req('/appointments',admin,{method:'POST',body:JSON.stringify(payload)});if(x.r.status!==201)throw Error('create failed '+JSON.stringify(x.b));a=x.b.appointment;if(!/^APT-\d{6}$/.test(a.appointmentId))throw Error('id invalid');
 x=await req('/appointments',admin,{method:'POST',body:JSON.stringify({...payload,patientId:p.id,reason:'Double booking'})});if(x.r.status!==409||x.b.error.code!=='DOCTOR_DOUBLE_BOOKED')throw Error('double booking allowed');
 x=await req(`/appointments/${a.appointmentId}`,admin);if(x.r.status!==200)throw Error('read failed');
 x=await req(`/appointments/${a.id}`,admin,{method:'PATCH',body:JSON.stringify({notes:'Updated notes'})});if(x.b.appointment.reason!==payload.reason)throw Error('partial reset');
 const q=new URLSearchParams({search:'Phase 5 verification',status:'Scheduled',doctorId:d.id,dateFrom:tomorrow,dateTo:tomorrow});x=await req(`/appointments?${q}`,admin);if(!x.b.appointments.some(v=>v.id===a.id))throw Error('search failed');
 if((await req(`/appointments/${a.id}`,admin,{method:'DELETE'})).r.status!==204)throw Error('delete failed');a=null;
 }finally{if(a)await req(`/appointments/${a.id}`,admin,{method:'DELETE'});if(p)await req(`/patients/${p.id}`,admin,{method:'DELETE'});if(d)await req(`/doctors/${d.id}`,admin,{method:'DELETE'});}console.log('Phase 5 smoke test passed: appointment CRUD, all authorized roles, search, and database double-booking prevention work.');};run().catch(e=>{console.error(e);process.exitCode=1;});
